Repository AstroNvim/AstroNvim, pull requests merged in 2022-07, with the labels that each got.

#730 fix: load packer compilation during bootstrap stage
  init.lua
  lua/core/bootstrap.lua
  lua/core/options.lua
  lua/core/plugins.lua
  lua/core/utils/init.lua
Labels: bug

#734 chore(lsp): remove unnecessary lines in lsp mappings
  lua/configs/lsp/handlers.lua
Labels: cleanup

#736 feat(lsp): allow user to configure default capabilities and flags for LSP
  lua/configs/lsp/handlers.lua
Labels: enhancement

#741 fix(sumneko_lua): Add AstroNvim config folder to sumneko_lua workspace
  lua/configs/lsp/server-settings/sumneko_lua.lua
  lua/core/utils/init.lua
Labels: bug

#743 fix(neo-tree): signcolumn not re-enabled after neo-tree directory highjack
  lua/configs/neo-tree.lua
Labels: bug

#792 chore(stylua): `no_call_parentheses` -> `call_parentheses`
  .stylua.toml
Labels: cleanup

#811 fix(core): improve error reporting on failed loaded user module
  lua/core/utils/init.lua
Labels: bug
