Repository AstroNvim/AstroNvim, pull requests merged in 2022-04, with the labels that each got.

#249 improve cmp lazy loading
  lua/core/plugins.lua
Labels: enhancement

#250 Move from dressing to NUI vim ui
  init.lua
  lua/core/defaults.lua
  lua/core/plugins.lua
  lua/core/ui.lua
  lua/user_example/init.lua
Labels: enhancement

#251 Fix vim.ui.select when formatting isn't specifically defined in options
  lua/core/ui.lua
Labels: bug

#253 Add automatic indent detection
  lua/configs/indent-o-matic.lua
  lua/core/plugins.lua
Labels: enhancement

#259 Fix focusing on window pop up
  lua/core/ui.lua
Labels: bug

#260 Generalize plugin enable/disable API
  .luacheckrc
  init.lua
  lua/core/autocmds.lua
  lua/core/mappings.lua
  lua/core/utils.lua
Labels: enhancement

#263 Add rebranding annoucement
  README.md
Labels: documentation

#266 Add missing telescope which-key bindings
  lua/configs/which-key.lua
Labels: bug

#267 Allow whichkey to not load menus for plugins that aren't loaded
  init.lua
  lua/configs/which-key-register.lua
  lua/configs/which-key.lua
  lua/core/mappings.lua
Labels: enhancement

#268 Fix updated session bindings
  lua/core/mappings.lua
Labels: bug

#271 fix telescope plugin check
  lua/configs/which-key-register.lua
Labels: bug

#274 Move binding setting to which-key for easier user override in config
  lua/configs/which-key-register.lua
  lua/core/mappings.lua
Labels: enhancement

#275 Fix typo in neotree configuration
  lua/configs/neo-tree.lua
Labels: bug

#277 Fix cmp lazy loading
  lua/configs/lsp/handlers.lua
  lua/core/plugins.lua
Labels: enhancement

#278 Add ability to put user config in ~/.config/astrovim/lua/user
  init.lua
  lua/core/utils.lua
Labels: enhancement

#284 Fix breaking cmp changes
  lua/configs/cmp.lua
Labels: bug

#287 fix packer rebase git command
  lua/core/plugins.lua
Labels: bug

#292 Improve modularity of cmp sources while maintaining priority
  lua/configs/cmp.lua
  lua/core/defaults.lua
  lua/core/plugins.lua
  lua/core/utils.lua
  lua/user_example/init.lua
Labels: enhancement

#293 Add optional requirements for default set up
  README.md
Labels: documentation

#300 Extend ToggleTerminal function and access
  lua/core/utils.lua
Labels: enhancement

#302 Augroup argument error fix
  lua/user_example/init.lua
Labels: bug

#303 Create issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: documentation

#304 Fix dashboard status autocmd
  lua/configs/dashboard.lua
  lua/core/autocmds.lua
Labels: bug

#305 Improve dashboard autocommand creation criteria
  lua/core/autocmds.lua
Labels: enhancement

#308 Move to built in filetype lua with neovim 0.7
  lua/configs/filetype.lua
  lua/core/options.lua
  lua/core/plugins.lua
  lua/user_example/init.lua
Labels: enhancement

#307 Add optional terminal numbers to toggle term
  lua/core/utils.lua
Labels: enhancement

#311 Augroup bug fix
  lua/core/autocmds.lua
Labels: bug

#312 Fix lsp config to v0.1.3
  lua/core/plugins.lua
Labels: bug

#316 Make dev icons follow theme instead of hard coding
  lua/configs/icons.lua
  lua/default_theme/colors.lua
  lua/default_theme/others.lua
Labels: enhancement

#317 Clean up status checking
  lua/configs/autopairs.lua
  lua/configs/better_escape.lua
  lua/configs/bufferline.lua
  lua/configs/cmp.lua
  lua/configs/colorizer.lua
  lua/configs/comment.lua
  lua/configs/gitsigns.lua
  lua/configs/indent-line.lua
  lua/configs/indent-o-matic.lua
  lua/configs/lsp/init.lua
  lua/configs/lsp/lsp-installer.lua
  lua/configs/lualine.lua
  lua/configs/luasnip.lua
  lua/configs/neo-tree.lua
  lua/configs/neoscroll.lua
  lua/configs/notify.lua
  lua/configs/smart-splits.lua
  lua/configs/telescope.lua
  lua/configs/toggleterm.lua
  lua/configs/treesitter.lua
  lua/configs/which-key-register.lua
  lua/configs/which-key.lua
  lua/core/plugins.lua
Labels: cleanup

#318 Add descriptions to user commands
  lua/configs/lsp/handlers.lua
  lua/core/autocmds.lua
Labels: enhancement

#320 remove unnecessary bufferline highlight group definitions
  lua/configs/bufferline.lua
Labels: cleanup

#321 Removed a lot of unnecessary redefinition of defaults and setup cleanup
  lua/configs/better_escape.lua
  lua/configs/bufferline.lua
  lua/configs/cmp.lua
  lua/configs/gitsigns.lua
  lua/configs/lualine.lua
  lua/configs/neo-tree.lua
  lua/configs/neoscroll.lua
  lua/configs/notify.lua
  lua/configs/smart-splits.lua
  lua/configs/symbols-outline.lua
  lua/configs/treesitter.lua
  lua/configs/which-key.lua
Labels: cleanup

#325 Another stab at fixing packer rebasing
  lua/core/plugins.lua
Labels: bug

#333 Add fzy plugin if user is on windoze
  lua/core/plugins.lua
Labels: enhancement

#334 Add description to each mapping
  lua/core/mappings.lua
Labels: enhancement

#335 Fix telescope live grep optional dependency
  README.md
Labels: documentation

#336 Detail visual in dashboard
  lua/configs/dashboard.lua
Labels: bug

#345 Fix telescope stack overflow
  lua/core/ui.lua
Labels: bug

#346 Fix lingering on_choice function
  lua/core/ui.lua
Labels: bug

#347 Clean up new telescope fix
  lua/core/ui.lua
Labels: cleanup

#351 Generalize which-key registration
  lua/configs/which-key-register.lua
  lua/core/mappings.lua
Labels: enhancement

#352 Update which-key example in user_example
  lua/user_example/init.lua
Labels: documentation

#358 Clean up autocommands
  lua/core/autocmds.lua
Labels: cleanup

#360 Rename comment to Comment
  lua/configs/Comment.lua
  lua/core/plugins.lua
Labels: cleanup

#366 Added URL highlighting
  lua/configs/highlighturl.lua
  lua/core/plugins.lua
  lua/default_theme/others.lua
Labels: enhancement

#368 Simplify highlight URL setting
  lua/configs/highlighturl.lua
  lua/core/plugins.lua
Labels: cleanup

#372 Add markdown highlighting
  lua/default_theme/others.lua
  lua/default_theme/treesitter.lua
Labels: enhancement

#373 Implement lua based URL highlighting
  lua/configs/which-key-register.lua
  lua/core/autocmds.lua
  lua/core/mappings.lua
  lua/core/options.lua
  lua/core/plugins.lua
  lua/core/utils.lua
Labels: enhancement

#374 Conform to the new lsp-installer API
  lua/configs/lsp/lsp-installer.lua
  lua/configs/nvim-lsp-installer.lua
  lua/core/plugins.lua
Labels: enhancement

#375 Update user_example for server registration override
  lua/user_example/init.lua
Labels: documentation

#376 Remove all old lsp-installer APIs
  lua/configs/lsp/handlers.lua
  lua/configs/lsp/init.lua
  lua/configs/lsp/lsp-installer.lua
  lua/core/plugins.lua
  lua/user_example/init.lua
Labels: enhancement

#378 Add LSP Extension Plugin Compatibility
  lua/configs/lsp/handlers.lua
  lua/configs/lsp/init.lua
Labels: enhancement

#382 Pin neo-tree for stability
  lua/core/plugins.lua
Labels: cleanup

#384 Clean up some stutter with the new lazy load stuff
  lua/core/plugins.lua
Labels: bug

#385 Reorder lsp plugin loading with new lsp-installer API
  lua/core/plugins.lua
Labels: bug

#390 fix which-key loading
  lua/core/plugins.lua
Labels: bug

#392 Unpin lspconfig
  lua/core/plugins.lua
Labels: cleanup

#393 Add filetype_extend luasnip configuration option
  lua/configs/luasnip.lua
  lua/user_example/init.lua
Labels: enhancement

#386 Move from Symbols Outline to Aerial
  lua/configs/aerial.lua
  lua/configs/lsp/handlers.lua
  lua/configs/symbols-outline.lua
  lua/configs/which-key-register.lua
  lua/core/mappings.lua
  lua/core/plugins.lua
  lua/default_theme/others.lua
Labels: enhancement
