Repository AstroNvim/AstroNvim, pull requests merged in 2022-05, with the labels that each got.

#414 clean up default options
  lua/core/options.lua
Labels: cleanup

#425 Removed deprecated LSP resolved_capabilities
  lua/configs/lsp/handlers.lua
  lua/user_example/init.lua
Labels: cleanup

#426 Streamline options setting and automatically check for colorscheme
  lua/core/mappings.lua
  lua/core/options.lua
  lua/core/utils.lua
  lua/user_example/init.lua
Labels: enhancement

#429 add fallback mappings for split movement and resize
  lua/core/mappings.lua
Labels: enhancement

#431 Add vim-bbye fallback binding
  lua/configs/which-key-register.lua
  lua/core/mappings.lua
Labels: enhancement

#432 Move builtins to the more general options file
  init.lua
  lua/core/options.lua
  lua/core/utils.lua
Labels: cleanup

#435 Move from vim-bbye to bufdelete.nvim
  lua/configs/which-key-register.lua
  lua/core/mappings.lua
  lua/core/plugins.lua
Labels: enhancement

#439 remove deprecated cmp native_menu
  lua/configs/cmp.lua
Labels: cleanup

#441 Clean up how disabled builtin plugins look
  lua/core/options.lua
Labels: cleanup

#449 Clean up cursorline autocommands
  lua/core/autocmds.lua
Labels: cleanup

#450 Fix race condition in autocommand
  lua/core/autocmds.lua
Labels: bug

#451 Remove cursorline autocommands
  lua/core/autocmds.lua
Labels: bug

#453 Bufferline reorder buffer mappings
  lua/core/mappings.lua
Labels: bug

#458 clean up more unnecessary defaults
  lua/configs/autopairs.lua
  lua/configs/cmp.lua
  lua/configs/which-key.lua
Labels: cleanup

#459 Revert back to just using resolved_capabilities
  lua/configs/lsp/handlers.lua
  lua/user_example/init.lua
Labels: bug

#460 Remove screenshots
  README.md
  screenshots/preview1.png
  screenshots/preview2.png
  screenshots/preview3.png
Labels: cleanup

#462 Remove terminal binding autocmd
  lua/core/mappings.lua
Labels: bug, cleanup

#465 Move lsp bindings to on_attach
  lua/configs/lsp/handlers.lua
  lua/core/mappings.lua
Labels: cleanup

#468 Add API for adding rules to nvim-autopairs
  lua/configs/autopairs.lua
Labels: enhancement

#470 fix null_ls autoformat with multiple files open
  lua/user_example/init.lua
Labels: bug

#473 Add lazy loading to alpha
  lua/core/autocmds.lua
  lua/core/plugins.lua
Labels: enhancement

#480 Fix alpha autocmd on start
  lua/core/autocmds.lua
Labels: bug

#484 Move plugin setup to the correct location
  lua/configs/indent-line.lua
  lua/configs/neo-tree.lua
  lua/core/options.lua
  lua/core/plugins.lua
  lua/core/utils.lua
Labels: cleanup

#487 fixed require for indent-line.lua
  lua/configs/indent-line.lua
Labels: bug

#489 Make lsp installer mappings always available
  lua/configs/lsp/handlers.lua
  lua/core/mappings.lua
Labels: bug

#491 Don't show which-key popup when Telescope window is opened
  lua/configs/which-key.lua
Labels: bug

#495 Telescope whichkey fix
  lua/configs/which-key.lua
Labels: bug

#496 Fix outdated indent blankline option name
  lua/configs/indent-line.lua
Labels: cleanup

#497 Move indent blankline options to setup call
  lua/configs/indent-line.lua
  lua/core/plugins.lua
Labels: cleanup

#501 Add lsp omnifunc
  lua/configs/lsp/handlers.lua
Labels: enhancement

#503 Alpha respect user tabline with autocommands
  lua/core/autocmds.lua
Labels: enhancement

#504 Simplify aerial config
  lua/configs/aerial.lua
Labels: cleanup

#505 Use default better escape bindings
  lua/configs/better_escape.lua
Labels: cleanup

#506 Clean up bufferline config
  lua/configs/bufferline.lua
  lua/default_theme/others.lua
Labels: cleanup

#509 Fix bug in user cmp add source function
  lua/core/utils.lua
Labels: bug

#511 lazy load schemastore on module
  lua/core/plugins.lua
Labels: cleanup

#512 Remove alpha plugins footer because it's wrong
  lua/configs/alpha.lua
Labels: cleanup

#516 add icons to increase accessibility
  lua/configs/nvim-lsp-installer.lua
Labels: enhancement

#525 chore(lsp): Cleanup lsp buffer mappings
  lua/configs/lsp/handlers.lua
Labels: cleanup

#528 fix(comment): fix Comment.nvim lazy loading
  lua/core/plugins.lua
Labels: bug

#537 fix(mappings): prompt when closing unsaved buffers
  lua/core/mappings.lua
Labels: bug

#538 feat(feline): show null-ls providers in feline
  lua/configs/feline.lua
  lua/core/status.lua
  lua/core/utils.lua
Labels: enhancement

#539 refactor(feline): cleaned up lsp client name provider
  lua/core/status.lua
Labels: cleanup

#540 chore(cinnamon): use plugins default configuration
  lua/configs/cinnamon.lua
Labels: cleanup

#541 chore(utils): add_user_cmp_source add priority to table format
  lua/core/utils.lua
Labels: cleanup

#542 feat(cmp): add user config for extension cmp setup calls
  lua/configs/cmp.lua
  lua/core/utils.lua
Labels: enhancement

#545 revert: move back to fzy-native for windows
  lua/core/plugins.lua
Labels: bug

#548 chore(feline): truncate null_ls sources if there isn't enough room
  lua/configs/feline.lua
  lua/core/status.lua
Labels: cleanup

#560 chore(core): add backspace nostop default
  lua/core/options.lua
Labels: cleanup

#563 fix(cmp): don't select automatically on enter
  lua/configs/cmp.lua
Labels: bug

#562 chore(bufferline): make selected buffer noticeable in bufferline
  lua/default_theme/plugins/bufferline.lua
Labels: cleanup

#568 chore(neo-tree): close neovim if neotree is last window
  lua/configs/neo-tree.lua
Labels: cleanup

#566 chore(cmp): improve lazy loading of snippets and cmp
  lua/core/plugins.lua
Labels: cleanup

#573 chore(docs): add funding link
  .github/FUNDING.md
Labels: documentation
