Repository AstroNvim/AstroNvim, pull requests merged in 2022-08, with the labels that each got.

#789 mappings and which-key
  lua/user_example/init.lua
Labels: documentation

#818 fix(status): fix bug in treesitter detection
  lua/core/status.lua
Labels: bug

#793 feat: move to mason package manager
  lua/configs/indent-line.lua
  lua/configs/lsp/init.lua
  lua/configs/mason-lspconfig.lua
  lua/configs/mason-tool-installer.lua
  lua/configs/mason.lua
  lua/configs/nvim-lsp-installer.lua
  lua/core/mappings.lua
  lua/core/plugins.lua
  lua/user_example/init.lua
Labels: enhancement

#824 fix(telescope,alpha): search icon on iTerm2
  lua/configs/alpha.lua
  lua/configs/telescope.lua
Labels: cleanup

#829 feat: better syntax highlighting for rust
  lua/default_theme/treesitter.lua
Labels: enhancement

#831 fix(lsp): fix lazy loading to help language servers attach automatically
  lua/core/plugins.lua
Labels: bug

#833 feat(mason): allow newly installed LSP to be loaded without restart
  lua/configs/lsp/handlers.lua
  lua/configs/lsp/init.lua
  lua/configs/mason-lspconfig.lua
  lua/core/plugins.lua
Labels: enhancement

#834 chore: specify that only stable neovim is supported
  .github/README.md
Labels: documentation

#854 feat(cmp): change item selection behaviour in menu
  lua/configs/cmp.lua
  lua/default_theme/base.lua
Labels: enhancement

#856 feat(cmp): use lspkind for cmp icons
  lua/configs/cmp.lua
  lua/core/plugins.lua
Labels: enhancement

#861 feat(updater): add AstroReload command
  lua/core/autocmds.lua
  lua/core/utils/updater.lua
Labels: enhancement

#863 chore: use lspkind icons for both cmp and aerial
  lua/configs/aerial.lua
  lua/configs/cmp.lua
  lua/configs/lspkind.lua
  lua/core/plugins.lua
Labels: cleanup

#874 feat(lsp): add visual mode lsp code formatting mapping
  lua/configs/lsp/handlers.lua
  lua/configs/which-key-register.lua
  lua/core/utils/init.lua
Labels: enhancement

#882 chore(lsp): make diagnostics focusable but not focused by default
  lua/configs/lsp/init.lua
Labels: cleanup

#885 fix(mappings): update Comment.nvim mappings to new API
  lua/core/mappings.lua
Labels: bug

#894 feat(default_theme): set terminal colors for use with neovide
  lua/default_theme/colors.lua
  lua/default_theme/init.lua
Labels: enhancement

#895 fix(autocmds): improve sidebar auto quitting autocmd
  lua/core/autocmds.lua
Labels: bug

#896 feat(session_manager): auto save previous session by default
  lua/configs/session_manager.lua
Labels: enhancement

#899 chore: move to form github issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/question.yaml
Labels: cleanup

#909 chore: allow users to create colorschemes without conflict
  .gitignore
Labels: enhancement

#933 feat(mappings): add lsp mappings for going to type definition and searching workspace symbols
  lua/configs/lsp/handlers.lua
  lua/core/mappings.lua
Labels: enhancement
